### ISSUE TITLE
ChatItem color bleeds when using &r to reset formatting

### ISSUE THREAD

**Issue by codeHusky** [dadus33/ChatItem#100]
When using `&r` to reset color codes and formatting in a chat formatting with LPC, ChatItem will fail to prevent colors from "bleeding" at that point and will misformat the message.

Using LPC and ChatItem 2.4.8
LPC format config: 
`chat-format: "&e{prefix}{displayname}&r: {message}"`
Result: 
![image](https://github.com/dadus33-plugins/ChatItem/assets/6946558/93b70d04-b14f-4cda-bd7d-73356403a417)

Revised LPC format config (workaround)
`chat-format: "&e{prefix}{displayname}&r&f: {message}"`
Result:
![image](https://github.com/dadus33-plugins/ChatItem/assets/6946558/0c66f8ff-ab5a-4c3a-82eb-6c805a7495ae)

**Comment by redbau** [comment]
Both my before and after messages are &7 and &8 respectively, no matter what I do.

Help! I'd like to have white text before and after the item. Is this possible?

**Comment by Elikill58** [comment]
This commit https://github.com/dadus33-plugins/ChatItem/commit/746b3b58a0187bddc3aee2495a1ff861ad6cf083 should fix all staying issues, else please create new issue :)
