### ISSUE TITLE
ChatItem overriding my chat format

### ISSUE THREAD

**Issue by ImNotStable** [dadus33/ChatItem#117]
![image](https://github.com/dadus33-plugins/ChatItem/assets/51060503/98145b6a-d4fb-4ba3-9f0d-ae83da90b0d5)

**Comment by ImNotStable** [comment]
I've tried using the MONITOR event-priority and it still does that.

**Comment by Elikill58** [comment]
You're using your own system ?
If Yes, I suggest you to use LOWEST and change the format by itself (aka `.setFormat()`) and `.setMessage()`. You can also change the manager used with `/chatitem select`, and maybe another would answer

**Comment by ImNotStable** [comment]
I've tried using both LOWEST and NORMAL. Just so you know I'm using this event specifically to change chat io.papermc.paper.event.player.AsyncChatEvent, I'm not sure if that matters.

**Comment by Elikill58** [comment]
Yes, that's matter. I'm personally using default bukkit events, maybe it's because of that

**Comment by ImNotStable** [comment]
Ah I rely on using components, that's why I use this event. I also have a chatcolor plugin. Not sure exactly what the plugin causing the issue would be.
