### ISSUE TITLE
[item] appears as number

### ISSUE THREAD

**Issue by FrancescoJacovo** [dadus33/ChatItem#122]
I'm using ChatControl Red plugin, i disabled the internal [item] variable that is limited (if the lines are too much the hover will be disabled) but when i try to use the [item] of ChatItem it'll replace the pkaceholder with a number between 0 and 5

**Comment by FrancescoJacovo** [comment]
any news?

**Comment by FrancescoJacovo** [comment]
do u have the jar to test it?

**Comment by Elikill58** [comment]
You can find dev build here: https://github.com/dadus33-plugins/ChatItem/actions/workflows/build.yml

**Comment by FrancescoJacovo** [comment]
Did it worked for u? it's still the same thing for us

**Comment by Elikill58** [comment]
Yes it worked for me, if you it doesn't, check latest dev build and give more details
