### ISSUE TITLE
Whole chat message is hoverable

### ISSUE THREAD

**Issue by daniel-skopek** [dadus33/ChatItem#123]
When I use for example [item] the whole message is hoverable. It would be great to make only [item] hoverable - not the whole message.

**Comment by Elikill58** [comment]
Sure. Can you give more details ? As server version, chat plugin used and debug content ?

**Comment by daniel-skopek** [comment]
Server version: 1.20.1 UniverseSpigot (fork of Pufferfish)
Using own chat plugin (only for formatting messages of AsyncPlayerChatEvent)

https://i.imgur.com/QC9iavM.gif
