### ISSUE TITLE
Add Support for Adventure Components

### ISSUE THREAD

**Issue by ImNotStable** [dadus33/ChatItem#125]
When a plugin uses the Paper API, uses AsyncChatEvent, and changes the chat format using the renderer method it causes unexpected behavior within chat when using `[item]`. This could prevent people from using your plugin.

**Comment by Elikill58** [comment]
It's doesn't seems to be because of Adventure not supported but the paper's event which is not supported

**Comment by ImNotStable** [comment]
I don't know what you mean when you say the paper event isn't supported?

**Comment by Elikill58** [comment]
yes, it's different that spigot's one, so it make something different

**Comment by ImNotStable** [comment]
Is there a way for you to add support for this?

**Comment by Elikill58** [comment]
Sure :)

**Comment by ImNotStable** [comment]
I found an easy way to do so in the latest version. (This uses the PaperAPI)

```java
  @EventHandler()
  public void on(AsyncChatEvent event) {
    Component message = event.message();
    ItemStack hand = event.getPlayer().getInventory().getItemInMainHand();
    message = message.replaceText(TextReplacementConfig.builder().match("\\[item\\]").replacement(hand.displayName().hoverEvent(hand.asHoverEvent())).build());
    event.message(message);
}
```
