### ISSUE TITLE
Add support for 1.20.6.

### ISSUE THREAD

**Issue by yxc0915** [dadus33/ChatItem#133]
Please add support for 1.20.6. I encountered an error with this version.
![image](https://github.com/dadus33-plugins/ChatItem/assets/62410385/1c87fbe2-43d1-4acc-839c-e81deaadd0fb)

**Comment by yxc0915** [comment]
This error message indicates that there was an issue initializing the main class me.dadus33.chatitem.ChatItem from the plugin file 'ChatItem-2.5.1.jar'. The specific error seems to be a java.lang.ArrayIndexOutOfBoundsException, meaning that the plugin is trying to access an index that is out of bounds for an array with a length of 3.

**Comment by yxc0915** [comment]
And I confirm that version 2.6.0-Dev also has this issue.

**Comment by Elikill58** [comment]
You can find version that can fix this here: https://github.com/dadus33-plugins/ChatItem/actions/runs/9164908404 or on discord
