### ISSUE TITLE
Error - Can't show my items in chat

### ISSUE THREAD

**Issue by PinoyLifeCraft** [dadus33/ChatItem#2]
09.07 17:08:02 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
09.07 17:08:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
09.07 17:08:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
09.07 17:08:02 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [Spigot.jar:git-Spigot-3fb9445-2b6c9f4]
09.07 17:08:02 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-3fb9445-2b6c9f4]
09.07 17:08:02 [Server] INFO at me.dadus33.chatitem.listeners.ChatPacketListener$1.run(ChatPacketListener.java:205) ~[?:?]
09.07 17:08:02 [Server] INFO at me.dadus33.chatitem.utils.ProtocolVersion.getClientVersion(ProtocolVersion.java:124) ~[?:?]
09.07 17:08:02 [Server] INFO java.lang.NullPointerException
09.07 17:08:02 [Server] INFO [17:08:02 WARN]: [ChatItem] Plugin ChatItem v1.3.5.6 generated an exception while executing task 56616
09.07 17:08:02 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
09.07 17:08:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
09.07 17:08:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
09.07 17:08:02 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [Spigot.jar:git-Spigot-3fb9445-2b6c9f4]
09.07 17:08:02 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-3fb9445-2b6c9f4]
09.07 17:08:02 [Server] INFO at me.dadus33.chatitem.listeners.ChatPacketListener$1.run(ChatPacketListener.java:205) ~[?:?]
09.07 17:08:02 [Server] INFO at me.dadus33.chatitem.utils.ProtocolVersion.getClientVersion(ProtocolVersion.java:124) ~[?:?]
09.07 17:08:02 [Server] INFO java.lang.NullPointerException
09.07 17:08:02 [Server] INFO [17:08:02 WARN]: [ChatItem] Plugin ChatItem v1.3.5.6 generated an exception while executing task 56615

I can't show my items in chat when I enter the placeholder.
I am using ChatControlPro I don't think so if that is the problem?
Can you fix it please 🙁

**Comment by dadus33** [comment]
Oh well, this is an old, recurring issue that kept giving me headaches ever since the first release of 1.3.5. It looks like I'll need to take a more drastic approach on this issue, possibly recoding that entire part. An update for the plugin shall be posted today, and the error should be fixed. Thank you for reporting!

**Comment by dadus33** [comment]
If you want to help with the release of the new version, you can join the discord chat and help us test: https://discord.gg/eQJbVJt

**Comment by PinoyLifeCraft** [comment]
Well thanks you reply, but I forgot my Discord account don't worry I'll try to retrieve it.

**Comment by dadus33** [comment]
@PinoyLifeCraft Your issue should finally be fixed with this update.
