### ISSUE TITLE
java.lang.IllegalAccessException and other errors when a player joins or leaves the server.

### ISSUE THREAD

**Issue by Quantum001** [dadus33/ChatItem#40]
I've been using this plugin on my public server for a few weeks now. I like this plugin, however there are some issues that result in console spam. [Here is a gist with my latest.log from a test server I spun up to reproduce the error.](https://gist.github.com/Quantum001/4d34c1f5b55ba7423b83792dd1d0f5f2) 
[Furthermore, here is the latest.log from my public server.](https://gist.github.com/Quantum001/ea9199ee3dd7d59034e7978127830130)

I am using **paper-1.18.2-313** and **ChatItem-2.2.1**

**Steps to reproduce:**
1.) Create new papermc server using version #311
2.) Install ChatItem 2.2.1 and restart server. 
3.) Have a player join the server and then leave.

**Comment by Elikill58** [comment]
Hi, sorry for the issue. Can you test latest dev build: https://github.com/dadus33-plugins/ChatItem/actions because I made few changes since update

**Comment by Quantum001** [comment]
This issue does not appear to be present in the ChatItem-2.2.2-SNAPSHOT build!

**Comment by Elikill58** [comment]
Perfectly ! I'm waiting approval of one change before making the update (that should come soon). I close this :)

**Comment by z0z0r4** [comment]
waiting your new build ,I found this waring too
https://mclo.gs/rP4NHfs
Is ChatItem-2.2.2-SNAPSHOT enable to use?

**Comment by Quantum001** [comment]
@z0z0r4 If you click on the link that Elikill58 posted, you can download the latest development build.
