### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by haer0248** [dadus33/ChatItem#5]
When I use **[item]** then chat bar will be displayed .... 
![default](https://user-images.githubusercontent.com/25150003/35215273-ae868432-ff9e-11e7-8f2d-b908bb5695c8.png)
My server plugin in : https://amsserver.xyz/online 
Please help me to fix the problem!

Server version: 1.12.2 spigot R0.1-SNAPSHOT

**Comment by dadus33** [comment]
Hey @haer0248 thanks for reporting the issue. I can see that the version of ChatItem you are using is 1.3.6.2, whereas the latest version is 1.3.6.3. The old version is known to show bugs on newer versions of 1.12. If that doesn't work though, be sure to include a link to your "latest.log" file located in the <server_root>/logs folder.
Thanks!

**Comment by haer0248** [comment]
OMG! This is my fault! I will download the latest version and to give it a try.

**Comment by haer0248** [comment]
I have updated the plugin, still the same...

**Comment by dadus33** [comment]
I see. Can you provide me with your latest.log file then? StackTraces don't always show in web based consoles because of "rate-limiters", that's why I'd like the log instead of a console paste. Thank you!

**Comment by haer0248** [comment]
https://goo[dot]gl/kA227j

**Comment by dadus33** [comment]
Can you please runt the command /protocol listeners and send me a screenshot with the output you get? Thanks.

**Comment by haer0248** [comment]
![default](https://user-images.githubusercontent.com/25150003/35332850-88436db2-0147-11e8-843e-517d961824c3.png)
nothing output.

**Comment by dadus33** [comment]
Alright, then it means that there is something wrong with your version of ProtocolLib or there is some other plugin interfering with it. Please proceed to download the latest dev build of ProtocolLib and try again: http://ci.dmulloy2.net/job/ProtocolLib/390/

**Comment by haer0248** [comment]
I use **4.4.0-SNAPSHOT-b390**
but you give **3.6.4**
want to lower the version?

**Comment by dadus33** [comment]
What? I didn't give you that version. In fact, I gave you 4.4.0 too, just like the one you have (https://i.imgur.com/pW3roaM.png).
But then it means something's wrong with the latest build, so try 4.3.0 (download from the spigot page).

**Comment by haer0248** [comment]
Ok I will try tomorrow.

**Comment by haer0248** [comment]
![default](https://user-images.githubusercontent.com/25150003/35384509-7d43cefc-0200-11e8-8b69-197791b7d0fd.png)
Thank you very much!

**Comment by dadus33** [comment]
Thank you for trying that out. Anyways, would you mind trying to re-download from the original link I posted (4.4.0)? From the looks of it, ProtocolLib wasn't registering packet listeners properly and for some reason didn't even seem to have any registered packages.

Firstly, the fact that the plugin seems to have been listening to PacketPlayOutSpawnEntityWeather although I set it to listen to the chat packet meant something was wrong with either ProtocolLib or another plugin possibly messing with it in some way. But the fact that ProtocolLib showed no listeners when running /protocol listeners just didn't make any sense, so it's very likely that you were using an outdated or modified version of ProtocolLib.
If that is not the case (please check by re-downloading from the link I sent), it means there is a problem with the latest version of ProtocolLib itself, and @dmulloy2 should be noticed about it.

**Comment by haer0248** [comment]
I remember as if a plugin is also needed, so I point his ProtocolLib download point, resulting in the installation of 4.4.0.
Thank you fix me problem.
