### ISSUE TITLE
Hover wrong padding

### ISSUE THREAD

**Issue by yipjunkai** [dadus33/ChatItem#51]
name-format: "&b{name}&7{amount}&r"
amount-format: " (x{times})"

![java_SadO6VK4he](https://user-images.githubusercontent.com/21007753/207230159-96d491c5-2bc2-4f26-8a6c-cb9bfd519901.png)

Hello,

I'm hovering on the white text on the right of the item name, yet the hover is still appearing.

Thank you.

**Comment by Elikill58** [comment]
Hi,

Did you tried dev build ?

**Comment by yipjunkai** [comment]
I was on 2.4.5, where can I get the dev build?

**Comment by Elikill58** [comment]
You can find it [here](https://github.com/dadus33-plugins/ChatItem/actions/workflows/build.yml) or in discord

**Comment by yipjunkai** [comment]
Yep, just tried it with the build from Commit [444d589](https://github.com/dadus33-plugins/ChatItem/commit/444d58900eb9ea75d8caf80741a810f7ce54a300).

When I hover on the text on the right of the item's name, the hover is still active

**Comment by Elikill58** [comment]
Fixed since 2.4.6
