### ISSUE TITLE
Getting kicked when linking item 1.19.3

### ISSUE THREAD

**Issue by whisperer195** [dadus33/ChatItem#53]
I assume there is no support for 1.19.3 but wanted to throw out that the plugin will kick everyone on the server when [I] is used, the item is displayed  in chat but with the wrong format, it shows in front and behind the player name. Error below. 
![Base Profile Screenshot 2022 12 21 - 01 47 48 12](https://user-images.githubusercontent.com/55124157/208839651-bcb6461e-4689-472c-afff-30d652510c76.png)

**Comment by Elikill58** [comment]
Can you tried dev build from [here](https://github.com/dadus33-plugins/ChatItem/actions/runs/3679381867) ?
