### ISSUE TITLE
ChatItem effects colors of suffixes and prefixes

### ISSUE THREAD

**Issue by RealTitanGod** [dadus33/ChatItem#59]
When using ChatItem it somehow modifies and messes with the colors of suffixes, prefixes and sometimes even nicknames.
See the exmaples below

How it normal looks:
<img width="351" alt="Screenshot_640" src="https://user-images.githubusercontent.com/48302092/213328536-7c2802e4-5b95-42d6-8555-c041eaa5fd55.png">

What ChatItem changes it too:
<img width="474" alt="Screenshot_639" src="https://user-images.githubusercontent.com/48302092/213328533-5c76b957-1d4a-48c7-8cfe-ddca00063d59.png">

Paper 1.19.2
ChatItem v2.4.5
LPC (LuckPerms Chat) v3.6.0

**Comment by Elikill58** [comment]
Can you tried dev build ? It's available on the discord or in the "actions" TAB on github

**Comment by RealTitanGod** [comment]
Just tried using the latest dev build and the issue still persists.
Its also now added a random number and odd symbol to the end.
<img width="354" alt="Screenshot_646" src="https://user-images.githubusercontent.com/48302092/213524172-da57dc50-bbe4-4dba-b12b-a590eb1edf2f.png">

**Comment by codeHusky** [comment]
same issue when using LPC on all same versions

**Comment by Elikill58** [comment]
Can be fixed with latest dev build. Don't forget to check with "Intercept packet" manager

**Comment by codeHusky** [comment]
@Elikill58 does not seem to be fixed on latest dev build, using intercept packet just breaks the message same as RealTitanGod's image

**Comment by codeHusky** [comment]
appears to be fixed on latest
