### ISSUE TITLE
Extreme error on login that kicks players

### ISSUE THREAD

**Issue by RainOfPain125** [dadus33/ChatItem#6]
This plugin in combination with another plugin (mcmmo action) unloads a big error into console everytime someone tries to join, and it kicks them

https://pastebin.com/HJ22Au7x

No idea why, no idea how. I'm just gonna uninstall the plugin for now.

**Comment by dadus33** [comment]
Hey @RainOfPain125 ! Thank you for reporting the issue. Unfortunately, the info you provided me with is simply not enough for me to understand what the issue might be. Does the plugin (MCMMO action) send some sort of message on user login? It can be any type of message (chat, title, subtitle, actionbar, anything). Also, Can you link me to the plugin page?

**Comment by RainOfPain125** [comment]
No, players are immediately kicked / don't even join before they can see any text, chat, titles, subtitles, anything. The only thing noticable is the error text in console.

https://www.spigotmc.org/resources/chatitem-display-items-in-chat.19064/

**Comment by dadus33** [comment]
What message are they kicked with? Also, you linked my plugin instead of the mcmmo one. Also, if my plugin is not installed, do they get any message from mcmmo?

**Comment by RainOfPain125** [comment]
@dadus33 Sorry, I was kinda all over the place yesterday.

You can close this, the other dev spotted the problem in this issue report here - https://github.com/games647/mcMMOAction/issues/21
