### ISSUE TITLE
Feature Request: Bungee Chatitem - Show items through BungeeChat

### ISSUE THREAD

**Issue by gaRt3n** [dadus33/ChatItem#7]
Hey there,

i was wondering if it's possible to send Items through BungeeChat with for example ChatControl Pro with ChatControl BungeeBridge.

It would be great when Using ChatItem on 2 Server to show them on both Servers.

**Comment by dadus33** [comment]
Hello, that feature has been requested before and will be part of the 1.3.7 update, along with many other changes.
