### ISSUE TITLE
FactionsUUID breaks chat with intercept packet

### ISSUE THREAD

**Issue by Eqxinus** [dadus33/ChatItem#74]
Could you add FactionsUUID support?
factions {
    chat {
        allianceChatFormat="§d%s:§f %s"
        alwaysShowChatTag=false #########################################
        broadcastDescriptionChanges=false
        broadcastTagChanges=false
        factionChatFormat="%s:§f %s"
        # Allow for players to chat only within their faction, with allies, etc.
        # Set to false to only allow public chats through this plugin.
        factionOnlyChat=true
        modChatFormat="§c%s:§f %s"
        tagFormat="%s§f"
        # If true, disables adding of faction tag so another plugin can manage this
        tagHandledByAnotherPlugin=false
        tagInsertAfterString="-"
        tagInsertBeforeString=""
        tagInsertIndex=0
        tagPadAfter=true
        tagPadBefore=false
        tagRelationColored=true
        tagReplaceString="[FACTION]"
        # Add items here (comma-separated) for commands to listen to that will auto-return the user to public chat
        triggerPublicChatOnCommand=[]
        truceChatFormat="§5%s:§f %s"
alwaysShowChatTag=false #########################################

when this is enabled it puts the faction in front of the message and has relational placeholders and thats why my ChatItem is counting up it doesn't process the relational placeholder 

so it will show one message

%rel_factionsuuid_relation_color%FACTION SADASD : []3[]

FACTION SADASD : ACTUAL ITEM

**Comment by Eqxinus** [comment]
![image](https://user-images.githubusercontent.com/81351530/233849272-2de49a6b-19f8-419a-b48e-f02606161343.png)

here is an image if needed :)

**Comment by Elikill58** [comment]
With "Intercept packet" it's fixed. Can't fix else. Use "/chatitem select" if you want more help while choosing. Require latest dev build
