### ISSUE TITLE
Option to output inventory slots in chat.

### ISSUE THREAD

**Issue by mibby** [dadus33/ChatItem#9]
Would it be possible to add an option to output specific inventory slots so you can display multiple items in one chat message?

i.e. ```{item-1}``` being inventory slot 1

**Comment by dadus33** [comment]
Hey @mibby !
This has actually already been requested. Also, I actually managed to fully implement this in my current recoded version, which i still, unfortunately, far from complete.

**Comment by mibby** [comment]
Oh! Well let me know if you need any help testing. :) Glad to hear it is a future implementation and feature.
